# Generated by Django 2.2.1 on 2019-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
    ]
